### ISSUE TITLE
unable to handle more than 16 files?

### ISSUE THREAD

**Issue by mattsawyer77** [sindresorhus/gulp-debug#11]
Some background: I have a stream that concatenates over 100 files together using gulp-concat. I'm trying to make sure these are sorted first, so I am using gulp-sort. But I wanted to check the ordering of the files which might need to be customized.

Anyway, my task looks something like this:

```javascript
gulp.task('framework', function() {
    var dest = 'build/ui/js', stream; 
    stream = gulp.src(sourcePaths.framework) // contains a couple of globs
    .pipe(sort());
    if(args.debug) { // set to true outside this task
        stream.pipe(debug({ title: 'framework' }));
    }
    stream.pipe(concat('framework.js'))
    .pipe(gulp.dest(dest));
    return stream;
});
```
After 16 filenames have been output to the console, the task just stops and doesn't continue processing. If I reduce the number of files passed into src() to below 16, it seems to work fine.

**Comment by floatdrop** [comment]
This is looks like [`highWatermark`](https://nodejs.org/api/stream.html#stream_new_stream_readable_options) problem, but gulp-debug is not buffering incoming files, just passign them through. I think `sort()` is causing problems, because it needs to get all files, sort them and after that pass them on.

Can you remove `.pipe(sort())` line?

**Comment by mattsawyer77** [comment]
If I remove the sort line, everything works. However I think I am going to replace gulp-sort with gulp-order (which fits my use case better anyway), we'll see how that goes.
