### ISSUE TITLE
Files limit 16 lines per debug()

### ISSUE THREAD

**Issue by jmarceli** [sindresorhus/gulp-debug#26]
I don't know why but my `debug` output is limited only to 16 lines.
My task is really simple:
```
gulp.task('default', function() {
  gulp.src(['*/**']).pipe(debug());
});
```
but it lists only first 16 files. When I append another `.pipe(debug());` it lists 16 more lines and so on.

I don't know it it matters but I'm using also this in my gulpfile (but not in this specific task):
```
var argv         = require('minimist')(process.argv.slice(2));
var autoprefixer = require('gulp-autoprefixer');
var browserSync  = require('browser-sync').create();
var changed      = require('gulp-changed');
var concat       = require('gulp-concat');
var flatten      = require('gulp-flatten');
var gulp         = require('gulp');
var gulpif       = require('gulp-if');
var imagemin     = require('gulp-imagemin');
var jshint       = require('gulp-jshint');
var lazypipe     = require('lazypipe');
var less         = require('gulp-less');
var merge        = require('merge-stream');
var minifyCss    = require('gulp-minify-css');
var plumber      = require('gulp-plumber');
var rev          = require('gulp-rev');
var runSequence  = require('run-sequence');
var sass         = require('gulp-sass');
var sourcemaps   = require('gulp-sourcemaps');
var uglify       = require('gulp-uglify');
var monitorCtrlC = require('monitorctrlc');
var gutil        = require('gulp-util');
var ftp          = require('vinyl-ftp');
var debug        = require('gulp-debug');
```
Looking forward to any suggestions.

**Edit**
I commented out everything except: `argv, gulp, debug`, but it doesn't solve the problem so I belive it is some kind of `debug()` limitation.

**Comment by jmarceli** [comment]
That's strange it somehow magically fixes itself after running long `pipe(debug()).pipe(debug())...` line.

**Comment by richdougherty** [comment]
I had a similar problem with exactly 16 debug messages being printed. In my case it was because I was returning the wrong kind of value from the task, so Gulp thought the task had completed and I think the process was ended before the tasks had really finished. I was returning a successful promise holding an incomplete stream, so Gulp thought the task was finished. I fixed it by getting the return type of the task fixed up. In your case you might be fixing it by making the task run for longer with more pipes added.
